[metadata]
target_versions = ["777BEE235A9E8BDD9863F6741BC3AC54BB6A113B62B1D2E4D12BBE6DB963A914"]

#NOP the CSWGuiPartySelection::OnPanelAdded() call site to the stock party-selection shared-slot collapse routine in CSWGuiPartySelection::UpdateVisibleCharacters().
[[hooks]]
address = 0x0058BE29
type = "simple"
original_bytes = [0xE8, 0x42, 0x26, 0x00, 0x00]
replacement_bytes = [0x90, 0x90, 0x90, 0x90, 0x90]
