[patch]
id = "K2_music_fix"
name = "Music Volume Fix for KOTOR2"
version = "0.1.0"
author = "J"
description = "Disables audio ducking feature that causes music to be too quiet during dialogue."

requires = []

conflicts = []

[patch.supported_versions]
kotor2_gog_aspyr = "777BEE235A9E8BDD9863F6741BC3AC54BB6A113B62B1D2E4D12BBE6DB963A914"
kotor2_steam_aspyr = "6A522E71631DCEE93467BD2010F3B23D9145326E1E2E89305F13AB104DBBFFEF"
